sonar.projectKey=thanh_shopping
sonar.projectName=thanh_shopping
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes

# Coverage
sonar.coverage.exclusions=**/controller/**,**/view/**,**/app/**,**/utils/**
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.host.url=http://localhost:9000

